export const REQUEST_START = "REQUEST_START";

export const GET_REQUISITION_SUCCESS = "GET_REQUISITION_SUCCESS";
export const GET_REQUISITION_FAIL = "GET_REQUISITION_FAIL";

export const GET_SINGLE_REQUISITION_SUCCESS = "GET_SINGLE_REQUISITION_SUCCESS";
export const GET_SINGLE_REQUISITION_FAIL = "GET_SINGLE_REQUISITION_FAIL";

export const UPDATE_SINGLE_REQUISITION_SUCCESS =
  "UPDATE_SINGLE_REQUISITION_SUCCESS";
export const UPDATE_SINGLE_REQUISITION_FAIL = "UPDATE_SINGLE_REQUISITION_FAIL";

export const DELETE_REQUISITION_SUCCESS = "DELETE_REQUISITION_SUCCESS";
export const DELETE_REQUISITION_FAIL = "DELETE_REQUISITION_FAIL";

export const POST_REQUISITION_SUCCESS = "POST_REQUISITION_SUCCESS";
export const POST_REQUISITION_FAIL = "POST_REQUISITION_FAIL";

export const GET_FILTERS_SUCCESS = "GET_FILTERS_SUCCESS";
export const GET_FILTERS_FAIL = "GET_FILTERS_FAIL";

export const GET_REQUISITION_COUNT_SUCCESS = "GET_REQUISITION_COUNT_SUCCESS";
export const GET_REQUISITION_COUNT_FAIL = "GET_REQUISITION_COUNT_FAIL";

export const GET_DISCIPLINE_SUCCESS = "GET_DISCIPLINE_SUCCESS";
export const GET_DISCIPLINE_FAIL = "GET_DISCIPLINE_FAIL";

export const GET_OCCUPATION_SUCCESS = "GET_OCCUPATION_SUCCESS";
export const GET_OCCUPATION_FAIL = "GET_OCCUPATION_FAIL";

export const GET_SPECIALITY_SUCCESS = "GET_SPECIALITY_SUCCESS";
export const GET_SPECIALITY_FAIL = "GET_SPECIALITY_FAIL";

export const GET_SUBSPECIALITY_SUCCESS = "GET_SUBSPECIALITY_SUCCESS";
export const GET_SUBSPECIALITY_FAIL = "GET_SUBSPECIALITY_FAIL";

export const GET_RESUME_SUCCESS = "GET_RESUME_SUCCESS";
export const GET_RESUME_FAIL = "GET_RESUME_FAIL";

export const GET_RESUME_COMPARE_SUCCESS = "GET_RESUME_COMPARE_SUCCESS";
export const GET_RESUME_COMPARE_FAIL = "GET_RESUME_COMPARE_FAIL";

export const GET_RESUME_SHORTLIST_SUCCESS = "GET_RESUME_SHORTLIST_SUCCESS";
export const GET_RESUME_SHORTLIST_FAIL = "GET_RESUME_SHORTLIST_FAIL";

export const GET_EDUCATION_FILTER_SUCCESS = "GET_EDUCATION_FILTER_SUCCESS";
export const GET_EDUCATION_FILTER_FAIL = "GET_EDUCATION_FILTER_FAIL";

export const GET_EXPERIENCE_FILTER_SUCCESS = "GET_EXPERIENCE_FILTER_SUCCESS";
export const GET_EXPERIENCE_FILTER_FAIL = "GET_EXPERIENCE_FILTER_FAIL";

export const GET_TOOLS_FILTER_SUCCESS = "GET_TOOLS_FILTER_SUCCESS";
export const GET_TOOLS_FILTER_FAIL = "GET_TOOLS_FILTER_FAIL";

export const GET_SKILLS_FILTER_SUCCESS = "GET_SKILLS_FILTER_SUCCESS";
export const GET_SKILLS_FILTER_FAIL = "GET_SKILLS_FILTER_FAIL";

export const GET_CORPORATE_FILTER_SUCCESS = "GET_CORPORATE_FILTER_SUCCESS";
export const GET_CORPORATE_FILTER_FAIL = "GET_CORPORATE_FILTER_FAIL";

export const GET_RESUME_CONTACTED_SUCCESS = "GET_RESUME_CONTACTED_SUCCESS";
export const GET_RESUME_CONTACTED_FAIL = "GET_RESUME_CONTACTED_FAIL";

export const GET_COMPARE_SUCCESS = "GET_COMPARE_SUCCESS";
export const GET_COMPARE_FAIL = "GET_COMPARE_FAIL";

export const ADD_COMPARE_SUCCESS = "ADD_COMPARE_SUCCESS";
export const ADD_COMPARE_FAIL = "ADD_COMPARE_FAIL";

export const DELETE_COMPARE_SUCCESS = "DELETE_COMPARE_SUCCESS";
export const DELETE_COMPARE_FAIL = "DELETE_COMPARE_FAIL";

export const GET_SHORTLIST_SUCCESS = "GET_SHORTLIST_SUCCESS";
export const GET_SHORTLIST_FAIL = "GET_SHORTLIST_FAIL";

export const ADD_SHORTLIST_SUCCESS = "ADD_SHORTLIST_SUCCESS";
export const ADD_SHORTLIST_FAIL = "ADD_SHORTLIST_FAIL";

export const DELETE_SHORTLIST_SUCCESS = "DELETE_SHORTLIST_SUCCESS";
export const DELETE_SHORTLIST_FAIL = "DELETE_SHORTLIST_FAIL";

export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL";

export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";
